test_complex: test_complex.c complex.c complex.h
	gcc -Wall test_complex.c complex.c -o test_complex

alloc_free_set: alloc_free_set.c complex.c complex.h
	gcc -Wall alloc_free_set.c complex.c -o alloc_free_set

clean:
	rm -f test_complex
	rm -rf alloc_free_set

